# include(CMakePrintHelpers)

set(DDDMP_PUBLIC_HEADERS
"${CMAKE_CURRENT_SOURCE_DIR}/dddmp.h"
)

set(DDDMP_SOURCES
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpInt.h"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpBinary.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpNodeAdd.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpStoreCnf.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpConvert.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpNodeBdd.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpStoreMisc.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpDbg.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpNodeCnf.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpUtil.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpLoad.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpStoreAdd.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpLoadCnf.c"
"${CMAKE_CURRENT_SOURCE_DIR}/dddmpStoreBdd.c"
)

if(CUDD_BUILD_SHARED_LIBS)
  add_library(dddmp SHARED ${DDDMP_SOURCES})
else()
  add_library(dddmp STATIC ${DDDMP_SOURCES})
endif()

target_include_directories(dddmp PUBLIC
  ../cudd
  ../epd
  ../mtr
  ../st
  ../util
  ../dddmp
  ${CMAKE_CURRENT_BINARY_DIR}/..
)

# cmake_print_properties(
#   TARGETS dddmp 
#   PROPERTIES INCLUDE_DIRECTORIES
# )

set_target_properties(cudd PROPERTIES
  VERSION ${PROJECT_VERSION}
  SOVERSION ${PROJECT_VERSION_MAJOR}
  POSITION_INDEPENDENT_CODE ON
  CXX_VISIBILITY_PRESET hidden
  VISIBILITY_INLINES_HIDDEN ON
  PUBLIC_HEADER "${DDDMP_PUBLIC_HEADERS}"
)

install(TARGETS dddmp
  EXPORT cuddTargets
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Runtime
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Runtime 
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Development
  INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/cudd COMPONENT Development
)